### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by songoku119** [AngellusMortis/sxm-player#1]
* Discord SiriusXM Bot version: latest
* Python version: 3.5.3
* Operating System: Windows server 2016 || debian linux 9.8

### Description

When trying to setup the project following the provided instructions and simply running the --help command produces an error.

### What I Did

mortis-music --help
Traceback (most recent call last):
  File "/home/user/mortis-music/venv/bin/mortis-music", line 11, in <module>
    load_entry_point('mortis-music==0.1.0', 'console_scripts', 'mortis-music')()
  File "/home/user/mortis-music/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 489, in 
load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/user/mortis-music/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2843, in
 load_entry_point
    return ep.load()
  File "/home/user/mortis-music/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2434, in
 load
    return self.resolve()
  File "/home/user/mortis-music/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2440, in
 resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/user/mortis-music/venv/lib/python3.5/site-packages/mortis_music-0.1.0-py3.5.egg/mortis_music
/cli.py", line 197
    base_url = f"http://{host}:{port}"
                                     ^
SyntaxError: invalid syntax

**Comment by AngellusMortis** [comment]
Sorry I never saw this. 

Only Python 3.6+ (potentially only 3.7+ even). This project is still in development. I am not really set on the name or APIs or anything. It should be considered very unstable at the moment.

**Comment by AngellusMortis** [comment]
@songoku119 You should be able to check out https://github.com/AngellusMortis/sxm-discord now. I split this project into two projects. This one is just now the core SXM playback functionality. If you were looking for the bot functionality, check out that one. 

As a reminder, it is Python 3.6+ only.
